<template>
<!-- We would like you to render 12 NFTs in the desktop full width view, but limit it to 3 NFTs if mobile width (examples in the design)-->
<!-- Here you will see conditional rendering separating between mobile Nfts and normal. You may use your own logic for displaying the nfts between the mobile view and desktop-->
    <div class="options">
      <span>Items</span>
      <span>Activity</span>
    </div>
    <div>
        <div v-if="mobileNFTs && mobileNFTs.length > 0" class="row window-container">
            <div v-for="(item, index) in mobileNFTs" :key="index" :class="'col-md-' + col "> <!--This will loop through all the items in mobileNFTs Array-->
            <!--Display and style as appropriate-->
              <Nft :item="item" />
            </div>
        </div>
        <div v-else  class="row window-container">
            <!--You may display the normal NFTs as such -->
            <div v-for="(item, index) in GenerateNFTData" :key="index" :class="'col-md-' + col" > <!--This will loop through all the items in NFTs Array generated by the computed method and display what you want-->
                <!--Display and style as appropriate-->
              <Nft :item="item" />
            </div>
        </div>
    </div>
    <div class="collection">
      <h4>You’ve seen the all collection</h4>
      <div>
        <button>Gallery</button>
        <button>Got Back To Top</button>
      </div>
    </div>
</template>
<script>
import Nft from "../Nft"

export default {
  name: 'Home-NFT-Display',
  data() {
    return{
      mobileNFTs: [],
      col: 3
    }
  },
  components: {
    Nft
  },
  mounted () {
  },
  created () {
    window.addEventListener('resize', this.checkScreen) // On window resize: runs the checkScreen method
  },
  methods: {
    checkScreen () {
      // You will have to add to this method if you want the expected results. Or abandon it entirely and make your own
      this.windowWidth = window.innerWidth
      if (this.windowWidth <= 600) {
        this.mobileNFTs = this.GenerateNFTData.slice(0, 3)
        this.col = 12
      }else if (this.windowWidth > 600 && this.windowWidth < 930) {
        this.mobileNFTs = []
        this.col = 6
      }else if(this.windowWidth > 930 && this.windowWidth < 1180){
        this.col = 4
      }else{
        this.col = 3
      }
    },
  },
  computed: {
    GenerateNFTData() {
      const NFTs = []
      for(let i =1; i<= 12; i++){
        const randomId = Math.floor(Math.random() * 100)
        const rndInt = Math.floor(Math.random() * 5) + 1
        NFTs.push({
          id: randomId,
          name: `NFT-${i}`,
          artist: "Unknown Artist",
          price: 100,
          image: rndInt
        })
      }   
    // Generate NFT data and push into the NFT array
      // You can create a loop that loops through n NFTS generating the data with unique IDs
      // Use these generated NFTs to display on the market.
      /** NFT data should look something like:
       * name: 'NFT-1' where 1 is the value of i in your loop
       * artist: 'Unknown Artist'
       * price: 100 #you may keep this random
       * image: this should be any image of your choosing or selected from the shared XD file
       */
      return NFTs
    }
}
}
</script>

<style scoped>
  .window-container{
    display: flex;
    padding: 20px 90px 90px 90px;
  }
  .options{
    display: flex;
    justify-content: center;
    gap: 80px;
    margin: 50px 80px 0px 60px;
    width: 90%;
    border-bottom: 1px solid lightgray;
  }

  .options span:hover{
    color: #50B1B5;
    border-bottom: 3px solid #50B1B5;
    cursor: pointer;
  }

  .collection{
    width: 100%;
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 20px;
  }
  .collection button{
    background:rgba(80, 177, 181, 0.1);
    border-radius: 22px;
    font: normal normal bold 11px/14px Montserrat;
    color: #5FBDC1;
    width: 141px;
    height: 43px;
    margin-right: 20px;
    border: none;
  }

  .collection button:hover{
    background:rgba(80, 177, 181, 1);
    color: white;
  }
  @media (max-width: 428px) {
    .options{
      margin: 60px 0px 0px 0px;
      width: 100%;
    }
    .collection div{
      display: flex;
      flex-direction: column;
      gap: 10px;
    }
    .window-container{
      padding: 20px 72px 72px 72px;
      align-items: center;
      justify-content: center;
    }
  }
</style>